### ISSUE TITLE
Release on Stackage

### ISSUE THREAD

**Issue by expipiplus1** [adamgundry/uom-plugin#13]
Experimental packages are welcome, the only requirement being that they compile with everything else on Stackage; this would mean adding units-parser too.

**Comment by philderbeast** [comment]
>Anyone can add any package to Stackage but you may only add packages under your own name. It's highly encouraged that the actual package maintainer is also the Stackage maintainer, if that is not the case you should drop the package maintainer a note first.

From stackage maintainers, [adding a package](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package).

Adam do you have any objections to putting `uom-plugin` on stackage?

**Comment by philderbeast** [comment]
I can have a go at doing this if you'd like.

**Comment by adamgundry** [comment]
I certainly don't object to `uom-plugin` being on Stackage. Doesn't this require it to build on GHC 8.4, though? That currently isn't the case because of #43.

**Comment by philderbeast** [comment]
Nightly is out until we get a fix for #43 but we could [add it to an LTS snapshot](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package-to-an-lts-snapshot).

**Comment by adamgundry** [comment]
Ah, I didn't spot that option. Adding it to an LTS snapshot on 8.2 or earlier sounds fine. If you're willing to make this happen, even better! I'm looking at #43 but it may not be an easy fix.

**Comment by philderbeast** [comment]
Thanks for looking at #43. I'm hitting this when trying out `cabal new-build` in [flare-timing](https://github.com/BlockScope/flare-timing).

I'll have a go at adding `uom-plugin` to the latest LTS snapshot that I can a clean build with. This will have to be made under my name if I do it. Are you OK with that?

>Anyone can add any package to Stackage but you may only add packages under your own name
SEE: [Adding a package](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package).

**Comment by adamgundry** [comment]
Sure, that's fine. Thanks for your help!

**Comment by philderbeast** [comment]
Looks like I'll need to ask you to push a new release to hackage before I can request `uom-plugin` be added to stackage `lts-11.9`.

```
stack unpack uom-plugin-0.2.0.1
uom-plugin-0.2.0.1: download
Unpacked uom-plugin-0.2.0.1 to /.../uom-plugin/uom-plugin-0.2.0.1/
pdejoux@ubik ~/d/s/b/s/uom-plugin> cd uom-plugin-0.2.0.1/
pdejoux@ubik ~/d/s/b/s/u/uom-plugin-0.2.0.1> stack init --resolver lts-11.9
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./


Warning: Cabal file warning in
         /.../uom-plugin-0.2.0.1/uom-plugin.cabal@
         5:1: The field "description" is specified more than once at positions 5:1, 16:1
Selected resolver: lts-11.9
Resolver 'lts-11.9' does not have a matching compiler to build some or all of your package(s).
ghc-8.2.2 cannot be used for these packages:
    - uom-plugin
ghc version 8.2.2 found
    - uom-plugin requires >=7.9 && <8.2
template-haskell version 2.12.0.0 found
    - uom-plugin requires >=2.9 && <2.12

This may be resolved by:
    - Using '--omit-packages to exclude mismatching package(s).
    - Using '--resolver' to specify a matching snapshot/resolver
```

I also encountered a warning during the build. I'll send through a pull request for that too, #44.

**Comment by adamgundry** [comment]
I've released a new version 0.3.0.0 to Hackage. Hopefully that resolves the existing issues blocking a Stackage release.

**Comment by philderbeast** [comment]
I've made the [request](https://github.com/commercialhaskell/lts-haskell/issues/136) to add `uom-plugin` to LTS stackage despite finding minor [hlint failures](#48).

**Comment by philderbeast** [comment]
The plugin is now up on LTS stackage.

https://www.stackage.org/lts-11.15/package/uom-plugin-0.3.0.0

We still have some work to do around making the hlint test robust to changes in hlint.

https://github.com/commercialhaskell/lts-haskell/issues/136#issuecomment-399750836
